---
- name: Deleting environment OpenShift TestDrive@Dev{{ ':' }} based on file dev-openshift-definition.info
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - gce/authentication
     - gce/defaults
     - dev-openshift-definition.info
     - notification/slack_authentication
  tasks:
     - include: commons/setting_defaults.yaml

     - name: Deleting instance exists{{ ':' }} {{ master_definition.hostname }}
       gce:
         instance_names: "{{  master_definition.hostname }}"
         zone: "{{ zone }}"
         state: "absent"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: Deleting Docker Storage for{{ ':' }}{{  master_definition.hostname }}
       gce_pd:
         name: "{{  master_definition.hostname }}-docker"
         zone: "{{ zone }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: Deleting instance exists{{ ':' }} {{ infra_definition.hostname }}
       gce:
         instance_names: "{{ infra_definition.hostname }}"
         zone: "{{ zone }}"
         state: "absent"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: Deleting Docker Storage for{{ ':' }}{{ infra_definition.hostname }}
       gce_pd:
         name: "{{ infra_definition.hostname }}-docker"
         zone: "{{ zone }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: Deleting ALL Nodes instances
       gce:
         instance_names: "{{ item.hostname }}"
         zone: "{{ zone }}"
         state: "absent"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True
       with_items: "{{ nodes_definition }}"

     - name: Deleting ALL Nodes's docker storage
       gce_pd:
         name: "{{ item.hostname }}-docker"
         zone: "{{ zone }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True
       with_items: "{{ nodes_definition }}"

     - name: Notifying by Slack about sucessfully deletion
       slack: token={{ default_slack_token }} msg="TestDrive@Dev{{ ':'}} Environment was successfully deleted"
       when: default_slack_token is defined and default_slack_token is not none



