---
- name: Create VNC host for OpenShift Openshift@Ops{{ ':' }} 
  hosts: localhost
  connection: connection
  gather_facts: False
  vars_files:
     - gce/authentication
     - gce/defaults
     - notification/mail_authentication
  tasks:
     - include: commons/setting_defaults.yaml
       tags:
          - always
          
     - name: Clear users file
       file:
          state: absent
          path: "tmp/users.csv"
       tags:
          - create_servers

     - name: Creating nodes
       include: ./create-ops.yaml uid=user{{ item }}
       with_sequence: start=1 end={{ attendees }}
       tags:
          - create_servers

- name: Adding some playbooks for easy each Labs exercise
  hosts: openshift_master_group
  gather_facts: False
  vars_files:
     - gce/authentication
     - gce/defaults
     - notification/mail_authentication
  tasks:
     - name: Create directory /root/labs
       file: path=/root/labs state=directory 

     - name: Download all playbooks for labs
       uri: url=https://raw.githubusercontent.com/latam-tech-office/testdrive-openshift/master/labs/{{ item }}
            method=GET status_code=200 creates=True dest=/root/labs/{{ item }}
       with_items: 
             - prepare-cluster.yaml
             - ansible.cfg
             - reset-cluster.yaml

     - name: Adapt prepare-cluster.yaml to run with current user
       replace: path=/root/labs/prepare-cluster.yaml regexp="maltron" replace="{{ hostvars[inventory_hostname].user_id }}"


- name: Preparing all the hosts with a basic configuration
  hosts: all
  gather_facts: False
  vars_files:
     - gce/authentication
     - gce/defaults
     - notification/mail_authentication
  tasks:
     - name: Loading SSH KEY from localhost (if any)
       set_fact: ssh_key="{{ lookup('file','{{ ssh_key_file }}') }}"
       when: ssh_key_file is defined
       tags:
          - prepare

     - name: Copy a SSH Key (if does exist)
       lineinfile: dest=/root/.ssh/authorized_keys state=present create=yes line="{{ ssh_key }}"
       when: ssh_key is defined
       tags:
          - prepare

     - name: Make sure no subscription will be used
       command: subscription-manager unregister
       ignore_errors: True

     - name: Generating a list of repository for all hosts
       template: src=templates/openshift.repo.j2 dest=/etc/yum.repos.d/openshift.repo